### ISSUE TITLE
Working with Crystal Version Manager?

### ISSUE THREAD

**Issue by nsweeting** [crystal-lang-tools/atom-ide-crystal#3] opened 2016-09-09 15:50 UTC
Hi there,

I'm using crystal 0.19.0 with crenv. So I provided atom-crystal with /home/username/.crenv/versions/0.19.0/bin for the compiler executable directory. This doesn't seem to be working though. I am getting the following error:

'crystal' could not be spawned. Is it installed and on your path? If so please open an issue on the package spawning the process.

Any help on this would be appreciated.

**Comment by keplersj** [comment] 2016-09-10 06:56
I'll look into integrating crenv directly

**Comment by keplersj** [comment] 2017-08-10 02:29
@faustinoaq Thought's on crenv and scry?

**Comment by faustinoaq** [comment] 2017-08-10 09:39
I used to work with cenv but it uses LLVM 3.5,  Would be good a crenv without too old versions of LLVM and crystal.

I mean crenv can install crystal `0.7.0` I think is not too useful in the way this language evolves. Also LLVM 3.5 is generating wrong code see: https://github.com/crystal-lang/crystal/issues/4104

> So I provided atom-crystal with /home/username/.crenv/versions/0.19.0/bin for the compiler executable directory.

I think you should use `/embedded/bin` instead of just `/bin`

> Thought's on crenv and scry?

I think we can let to user specify the path for executable. If executable is in global path, then the extension should detect it and use it by default. By example:

```cson
# by default tries to detect if a executable is available.
crystal.compiler = 'crystal'
crystal.server = 'scry'
```

```cson
# If user doesn't have a executable in global path then need to specify path.
# I think this is good because user can specify versions per workspace
crystal.compiler = '/home/username/.crenv/versions/0.19.0/bin'
crystal.server = '/home/main/Projects/scry/scry'
```

Some of this configuration was an idea by @kofno inside Scry https://github.com/kofno/scry/blob/master/src/scry/protocol/settings.cr#L18
(see `command` and `backend`)

**Comment by faustinoaq** [comment] 2017-08-10 09:46
crenv binaries works as a normal executable, the problem is that `CRYSTAL_PATH` is empty.

```
$ ~/.anyenv/envs/crenv/versions/0.18.7/embedded/bin/crystal -v
Crystal 0.18.7 [68783f1] (2016-07-03)
$ ~/.anyenv/envs/crenv/versions/0.18.7/embedded/bin/crystal env
CRYSTAL_CACHE_DIR="/home/main/.cache/crystal"
CRYSTAL_PATH=""
CRYSTAL_VERSION="0.18.7
```

I think would be easier if user do `crenv global <version>` instead.

**Comment by faustinoaq** [comment] 2017-08-10 18:47
Hey Kepler, Do you think we can change the organization name from
atom-crystal to crystal-editor or maybe CrystalEditorSupport like
JuliaEditorSupport https://github.com/JuliaEditorSupport. So we can add
repositories for sublime, emacs, vim, vscode, atom, etc. All in one place
well documented easier to follow and maintain.  :-)

**Comment by keplersj** [comment] 2017-08-10 18:59
@faustinoaq I like this idea. Let's discuss it in the scry gitter.

**Comment by keplersj** [comment] 2018-03-07 22:58
@faustinoaq Where does this fall in relation to scry?

**Comment by faustinoaq** [comment] 2018-03-07 23:05
I don't think this issue is related to scry, but thanks to it we released Crystal Lang Tools organization :tada: 

I think if you want to use a specific crystal version then you should set you desired version as global, I remember crenv has an option for that.

**Comment by keplersj** [comment] 2018-03-07 23:20
Closing. Sounds like scry should support this out of the box, and this package is just a wrapper around scry now. Please, reopen if this isn't true.

**Closed as completed by keplersj** 2018-03-07 23:20 UTC
