### ISSUE TITLE
Atom does not exit correctly

### ISSUE THREAD

**Issue by vypxl** [crystal-lang-tools/atom-ide-crystal#32] opened 2018-03-28 08:28 UTC
### [Enter steps to reproduce:]

 - Start Atom Editor with installed package.
 - Open some project
 - Close Atom by CTRL-Q or system exit signal

**Atom**: 1.25.0 x64; updated today
**OS**: linux 4.15.8-1-ARCH

### Issue
After trying to close, Atom closes Treeview, hides the status bar and disables syntax highlighting, without beeing able to re-activate any. Another exit signal leads to exiting. After restart, Treeview is not shown unless by clicking on the arrow.

### Commands
####Non-Core Packages:
```
atom-ide-ui@0.9.4
atom-material-syntax@1.0.8
atom-material-syntax-dark@1.0.0
atom-material-ui@2.1.3
autosave-onchange@1.5.1
busy-signal@1.4.3
editorconfig@2.2.2
google-dark-syntax@3.3.0
haskell-ghc-mod@2.2.3
ide-crystal@0.3.3
ide-haskell@2.3.1
ide-rust@0.15.1
intentions@1.1.5
language-crystal-actual@0.37.2
language-haskell@1.17.3
language-rust@0.4.12
linter@2.2.0
linter-rust@0.8.4
linter-ui-default@1.7.1
vim-mode-plus@1.31.1
```

**Comment by keplersj** [comment] 2018-03-28 16:54
I'm not sure I understand how this is due to `ide-crystal`... This issue doesn't occur without `ide-crystal` installed?

**Comment by keplersj** [comment] 2018-03-28 16:57
I see that you have `linter`+`linter-ui-default`+`busy-signal`+`intentions` installed alongside `atom-ide-ui`. My first guess is that this could be causing your problem. `atom-ide-ui` is itself a `linter` consumer. Having them all installed at once could possibly create conflicts and other issues for your editor.

**Comment by keplersj** [comment] 2018-03-28 17:02
I also see that you have `ide-haskell` and `haskell-ghc-mod`. While compatible with Atom IDE, they are not totally integrated with it. (ref: https://github.com/atom-haskell/ide-haskell/issues/215) I recommend [`ide-haskell-hie`](https://atom.io/packages/ide-haskell-hie) for integrating Haskell with Atom IDE.

**Comment by vypxl** [comment] 2018-03-29 10:14
The issue does not occur without ide-crystal installed or when it's disabled. I will test your proposals later today

**Comment by keplersj** [comment] 2018-03-29 15:28
If you can't reproduce it without `ide-crystal` it is definitely at fault, and my other suggestions won't fix the problem. I'll try to reproduce it soon.

What I can't figure out of the top of my head is what makes `ide-crystal` different from `ide-rust` in this scenario. They both make use of the same `atom-languageclient` under the hood. Any thoughts @damieng?

**Comment by damieng** [comment] 2018-03-29 15:33
This can happen if the language server does not correctly respond to the shutdown message.

The same process happens when shutting down the server because it is no longer in use (i.e. close the last opened crystal file) and might be easier to troubleshoot as Atom isn't unloading at the time so you can see the debugging messages   (enable with `atom.config.set('core.debugLSP', true)` )

**Comment by keplersj** [comment] 2018-03-29 15:44
@faustinoaq Is Scry handling shutdown messages correctly? The only code I see that handles it is at https://github.com/crystal-lang-tools/scry/blob/4b699f6a7bce2fb2f866e0c2b4ab61fd4931491d/src/scry/context.cr#L25-L35

**Comment by damieng** [comment] 2018-03-29 16:13
I don't think it is - it's supposed to send a response to the shutdown message rather than just terminate.  

There is also an exit message which is supposed to do what Scry's current shutdown does.

https://microsoft.github.io/language-server-protocol/specification

**Comment by faustinoaq** [comment] 2018-03-29 19:05
> Is Scry handling shutdown messages correctly?

@keplersj I think so, although I don't know if scry is still full compatible with latest LSP specification

> I don't think it is - it's supposed to send a response to the shutdown message rather than just terminate.

@damieng Oh, you're right, seems scry isn't sending a shutdown response, I just remember I added `exit(0)` some time ago as a workaround :sweat_smile: 

BTW, these are my VSCode logs (working just fine)

```
D, [2018-03-29 13:59:03 -05:00 #6893] DEBUG -- : Content-Length: 58
D, [2018-03-29 13:59:03 -05:00 #6893] DEBUG -- : 
D, [2018-03-29 13:59:03 -05:00 #6893] DEBUG -- : {"jsonrpc":"2.0","id":1,"method":"shutdown","params":null}
I, [2018-03-29 13:59:03 -05:00 #6893]  INFO -- : ...your session has ended
```

Full logs here: [scry.out.tmNDE6.zip](https://github.com/crystal-lang-tools/atom-ide-crystal/files/1861554/scry.out.tmNDE6.zip)

**Comment by faustinoaq** [comment] 2018-03-29 19:05
BTW, Thank you for the PRs! :smile:

**Comment by keplersj** [comment] 2018-04-09 17:59
crystal-lang-tools/scry#69 and crystal-lang-tools/scry#71 have both been resolved. This issue should be fixed with the next update to `scry` and `ide-crystal`.

**Closed as completed** 2020-12-24 12:49 UTC
Labels: bug
